version: '3'
services:
  rabbitmq:
    container_name: rabbitmq
    image: tp2_rabbitmq:latest
    ports:
      - 15672:15672

  producer:
    container_name: client
    image: tp2_client:latest
    volumes:
      - ./client/files/questions_short.csv:/files/questions.csv
      - ./client/files/answers_short.csv:/files/answers.csv
      - ./client/config.yaml:/config.yaml
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    entrypoint: /client

  consumer1:
    container_name: input_interface_1
    image: tp2_input_interface:latest
    volumes:
      - ./inputInterface/config.yaml:/config.yaml
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    entrypoint: /inputInterface 
  
  consumer2:
    container_name: input_interface_2
    image: tp2_input_interface:latest
    volumes:
      - ./inputInterface/config.yaml:/config.yaml
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    entrypoint: /inputInterface 

  consumer3:
    container_name: input_interface_3
    image: tp2_input_interface:latest
    volumes:
      - ./inputInterface/config.yaml:/config.yaml
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    entrypoint: /inputInterface  

  filterPto1:
    container_name: filter_pto_1
    image: tp2_filter_pto_1:latest
    volumes:
      - ./filterPto1/config.yaml:/config.yaml
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    entrypoint: /filterPto1

  filterPto1_2:
    container_name: filter_pto_1_2
    image: tp2_filter_pto_1:latest
    volumes:
      - ./filterPto1/config.yaml:/config.yaml
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    entrypoint: /filterPto1       

  percentageCalculator1:
    container_name: percentageCalculator_1
    image: tp2_percentage_calculator:latest
    volumes:
      - ./percentageCalculator/config.yaml:/config.yaml
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    entrypoint: /percentageCalculator

  idDelivery:
    container_name: idDelivery
    image: tp2_id_delivery:latest
    volumes:
      - ./idDelivery/config.yaml:/config.yaml
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    entrypoint: /idDelivery

  groupBy1:
    container_name: groupBy1
    image: tp2_group_by:latest
    volumes:
      - ./groupBy/config.yaml:/config.yaml
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    entrypoint: /groupBy 

  groupBy1_2:
    container_name: groupBy1_2
    image: tp2_group_by:latest
    volumes:
      - ./groupBy/config_2.yaml:/config.yaml
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    entrypoint: /groupBy   

  topTenPto2:
    container_name: topTenPto2
    image: tp2_top_ten_pto2:latest
    volumes:
      - ./topTenPto2/config.yaml:/config.yaml
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    entrypoint: /topTenPto2

  join:
    container_name: join
    image: tp2_join:latest
    volumes:
      - ./join/config.yaml:/config.yaml
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    entrypoint: /join
  
  join_2:
    container_name: join_2
    image: tp2_join:latest
    volumes:
      - ./join/config_2.yaml:/config.yaml
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    entrypoint: /join

  join_3:
    container_name: join_3
    image: tp2_join:latest
    volumes:
      - ./join/config_3.yaml:/config.yaml
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    entrypoint: /join  

  duobleGroupBy:
    container_name: duobleGroupBy
    image: tp2_duoble_group_by:latest
    volumes:
      - ./duobleGroupBy/config.yaml:/config.yaml
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    entrypoint: /duobleGroupBy  
  
  topTenPto3:
    container_name: topTenPto3
    image: tp2_top_ten_pto3:latest
    volumes:
      - ./topTenPto3/config.yaml:/config.yaml
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    entrypoint: /topTenPto3   

  endSyncronizer:
    container_name: endSyncronizer
    image: tp2_end_syncronizer:latest
    volumes:
      - ./endSyncronizer/config.yaml:/config.yaml
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    entrypoint: /endSyncronizer      
