rabbitQueue:
  address: "amqp://guest:guest@rabbitmq:5672/"

input:
  questions: "input_q"
  answers: "input_a"

endSignal:
  questions: "end_q_i_interface"
  answers: "end_a_i_interface"
log:
  level: "info"
  
q_destinies: 
  #q_punto2:
  #  - "OwnerUserId"
  #  - "Score"  
  q_punto3:
    - "Id"
    - "CreationDate"
    - "Score"
    - "Tags"  
a_destinies:
  #a_punto1:
  #  - "Body"
  #  - "Score"
  #a_punto2:
  #  - "OwnerUserId"
  #  - "Score" 
  a_punto3:
    - "ParentId"
    - "CreationDate"
    - "Score"

q_punto3: 
  - "q_punto3"
  - "q_punto3_2"
  - "q_punto3_3"

a_punto3: 
  - "a_punto3"
  - "a_punto3_2"
  - "a_punto3_3"