q_destinies: 
    q_punto1:
      - "Body"
      - "Score"
    #q_punto2:
    #  - "OwnerUserId"
    #  - "Score"  
    #q_punto3:
    #  - "Id"
    #  - "CreationDate"
    #  - "Score"
    #  - "Tags"  
a_destinies: 
    #a_punto2:
    #  - "OwnerUserId"
    #  - "Score" 
    #a_punto3:
    #  - "ParentId"
    #  - "CreationDate"
    #  - "Score"
rabbitQueue:
  address: "amqp://guest:guest@rabbitmq:5672/"

input:
  questions: "input_q"
  answers: "input_a"

endSignal:
  input: 
    questions:
      qname: "end_3_2_q"
      nsignals: 1
    answers:
      qname: "end_3_2_a"
      nsignals: 1  
  output:
    questions:
      qname: "end_2_1_q"
      nsignals: 1
    answers:
      qname: "end_2_1_a"
      nsignals: 1  
log:
  level: "info"