jr_input: "join_output"
groupByOutput: "gb_output"
rabbitQueue:
  address: "amqp://guest:guest@rabbitmq:5672/"
endSignal:
  #input: 
  #    qname: "end_join"
  #    nsignals: 1  
  output:
      qname: "end_join"
      nsignals: 1
log:
  level: "info"